base_images:
  ocp-4:
    name: automation-flavors
    namespace: stackrox
    tag: openshift-4-0.10.0
  ubi-minimal:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
build_root:
  image_stream_tag:
    name: apollo-ci
    namespace: stackrox
    tag: stackrox-test-0.3.69
resources:
  '*':
    requests:
      cpu: 2000m
      memory: 4000Mi
test_binary_build_commands: .openshift-ci/dispatch.sh test-binary-build-commands
tests:
- as: ebpf-qa-e2e-tests
  steps:
    env:
      COLLECTION_METHOD: ebpf
      OCP_VERSION: ocp/stable-4.12
      TEST_SUITE: ocp-qa-e2e-tests
    workflow: stackrox-automation-flavors-ocp-4-e2e
  timeout: 5h0m0s
- as: merge-ebpf-qa-e2e-tests
  postsubmit: true
  steps:
    env:
      COLLECTION_METHOD: ebpf
      OCP_VERSION: ocp/stable-4.12
      TEST_SUITE: ocp-qa-e2e-tests
    workflow: stackrox-automation-flavors-ocp-4-e2e
  timeout: 5h0m0s
zz_generated_metadata:
  branch: jv-rox-23611-force-ebpf-collection-method-for-stackrox-ebpf-only-tests
  org: stackrox
  repo: stackrox
  variant: ocp-4-12
