build_root:
  image_stream_tag:
    name: collector-test
    namespace: stackrox
    tag: latest
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
ref:
- as: initjob
  commands: .openshift-ci/initjob/20-set-up-shared-environment.sh "$ARTIFACT_DIR/shared-env" 
  from: src
  resources:
    requests:
      cpu: 2000m
      memory: 4000Mi
workflow:
  as: lint-workflow
  cluster_profile: aws
  steps:
    pre:
    - ref: initjob
    test:
    - as: clang-format
      commands: make -C collector check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
    post:
    - as: post-lint
      commands: echo "post lint"
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
tests:
- as: lint
  steps:
    workflow: lint-workflow
    - as: shfmt-check
      commands: make shfmt-check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: test-scripts
  steps:
    test:
    - as: shellcheck-all
      commands: make shellcheck-all
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
zz_generated_metadata:
  branch: ROX-11208-collector-ci-migration-initjob
  org: stackrox
  repo: collector
