base_images:
  centos:
    name: centos
    namespace: origin
    tag: stream8
build_root:
  image_stream_tag:
    name: collector-test
    namespace: stackrox
    tag: latest
images:
- dockerfile_path: builder/Dockerfile
  from: centos
  inputs:
    src:
      paths:
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/collector
      - destination_dir: builder
        source_path: /go/src/github.com/stackrox/collector/builder/Dockerfile
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/collector/builder/install
      - destination_dir: .
        source_path: /go/src/github.com/stackrox/collector/builder/build
  to: collector-builder
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: lint
  steps:
    test:
    - as: clang-format
      commands: make -C collector check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
    - as: shfmt-check
      commands: make shfmt-check
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: test-scripts
  steps:
    test:
    - as: shellcheck-all
      commands: make shellcheck-all
      from: src
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
- as: collector
  steps:
    test:
    - as: build-collector
      commands: builder/build/build-collector.sh
      from: collector-builder
      resources:
        requests:
          cpu: 2000m
          memory: 4000Mi
zz_generated_metadata:
  branch: master
  org: stackrox
  repo: collector
